// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2Hg198ne8M2QzsCB0RlFKgXPRaSeixQ',
    appId: '1:341073172166:web:78056577564c6a525f69c7',
    messagingSenderId: '341073172166',
    projectId: 'neurodivergent-app-27db9',
    authDomain: 'neurodivergent-app-27db9.firebaseapp.com',
    storageBucket: 'neurodivergent-app-27db9.firebasestorage.app',
    measurementId: 'G-4N3ENFKVBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Gto6jHtFB0Vc6oTYpwyYld_VQ_fh1o',
    appId: '1:341073172166:android:013120e799573cdb5f69c7',
    messagingSenderId: '341073172166',
    projectId: 'neurodivergent-app-27db9',
    storageBucket: 'neurodivergent-app-27db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiLChxpY-W6D4Wmxuvny9zs7jno0tt9Kw',
    appId: '1:341073172166:ios:2578dc02a9a0f5885f69c7',
    messagingSenderId: '341073172166',
    projectId: 'neurodivergent-app-27db9',
    storageBucket: 'neurodivergent-app-27db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiLChxpY-W6D4Wmxuvny9zs7jno0tt9Kw',
    appId: '1:341073172166:ios:2578dc02a9a0f5885f69c7',
    messagingSenderId: '341073172166',
    projectId: 'neurodivergent-app-27db9',
    storageBucket: 'neurodivergent-app-27db9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2Hg198ne8M2QzsCB0RlFKgXPRaSeixQ',
    appId: '1:341073172166:web:c943eb15e90640125f69c7',
    messagingSenderId: '341073172166',
    projectId: 'neurodivergent-app-27db9',
    authDomain: 'neurodivergent-app-27db9.firebaseapp.com',
    storageBucket: 'neurodivergent-app-27db9.firebasestorage.app',
    measurementId: 'G-CWDLSH3RFJ',
  );
}
